### ISSUE TITLE
Does this work with mainnet?

### ISSUE THREAD

**Issue by flotti455** [freddiecoleman/chia-network-scanner#8]
I'm trying to get current version https://github.com/freddiecoleman/chia-network-scanner/tree/270c769c4d4a0a90f83be211ae74195a84705dd1 to work, using the provided README.md example.

Here is my adaption for mainnet:

```
#!/usr/bin/env ts-node

import { ChiaNetworkScanner } from 'chia-network-scanner';

const chiaNetworkScanner = new ChiaNetworkScanner({
    // The network to scan and protocol to use
    network: {
        networkId: 'mainnet',
        protocolVersion: '0.0.32',
        softwareVersion: '1.0.3'
    },

    startNodes: [{
        hostname: 'introducer.chia.net',
        port: 8444,
    }],

    // Identifies this peer on the network
    peer: {
        nodeType: 1,
    },

    // Used to timeout on various operations such as handshake
    connectionTimeout: 20000,

    // Number of peers to scan concurrently. Bigger is faster but uses more sockets and memory :)
    concurrency: 50,

    // Full node public key
    keyPath: '/home/mynode/.chia/mainnet/config/ssl/full_node/public_full_node.key',

    // Full node public cert
    certPath: '/home/mynode/.chia/mainnet/config/ssl/full_node/public_full_node.crt'
});

// const peers = await chiaNetworkScanner.scan();
console.log("test");
const peers = chiaNetworkScanner.scan();
console.log("test2");
```

* It fails on `await`/`yield` when `const peers = await chiaNetworkScanner.scan();`. Therefore i removed `await`.
* But then it fails on the first handshake: 

```
test
{"level":30,"time":1618061257044,"pid":481383,"hostname":"mynode","msg":"Starting scan of Chia Network"}
test2
{"level":30,"time":1618061257046,"pid":481383,"hostname":"mynode","visited":false,"hostname":"introducer.chia.net","port":8444,"timestamp":1618061257,"msg":"Visiting peer"}
{"level":30,"time":1618061257047,"pid":481383,"hostname":"mynode","visited":false,"hostname":"introducer.chia.net","port":8444,"timestamp":1618061257,"msg":"Establishing websocket connection"}
{"level":30,"time":1618061257047,"pid":481383,"hostname":"mynode","msg":"Attempting websocket connection to wss://introducer.chia.net:8444/ws"}
{"level":30,"time":1618061257785,"pid":481383,"hostname":"mynode","msg":"Established websocket connection to Chia node introducer.chia.net:8444"}
{"level":30,"time":1618061257785,"pid":481383,"hostname":"mynode","visited":false,"hostname":"introducer.chia.net","port":8444,"timestamp":1618061257,"msg":"Websocket connection established"}
{"level":30,"time":1618061257786,"pid":481383,"hostname":"mynode","msg":"Encoded handshake 01000000002c000000076d61696e6e657400000006302e302e333200000005312e302e3320fc010000000100010000000131"}
{"level":30,"time":1618061257786,"pid":481383,"hostname":"mynode","msg":"Sending 1 message"}
{"level":30,"time":1618061257952,"pid":481383,"hostname":"mynode","msg":"Received message of type 1"}
{"level":30,"time":1618061257952,"pid":481383,"hostname":"mynode","msg":"Decoded message to {\"network_id\":\"mainnet\",\"protocol_version\":\"0.0.32\",\"software_version\":\"1.0.3\",\"server_port\":8444,\"node_type\":5}"}
{"level":30,"time":1618061257952,"pid":481383,"hostname":"mynode","msg":"Encoded 43 2b0000000000"}
{"level":30,"time":1618061257952,"pid":481383,"hostname":"mynode","msg":"Sending 43 message"}
{"level":30,"time":1618061258119,"pid":481383,"hostname":"mynode","stack":"Error: 1\n    at WebSocket.ws.on (/home/mynode/git/typescript-node-minimal/node_modules/chia-network-scanner/MessageChannel.ts:77:61)\n    at WebSocket.emit (events.js:198:13)\n    at WebSocket.EventEmitter.emit (domain.js:448:20)\n    at WebSocket.emitClose (/home/mynode/git/typescript-node-minimal/node_modules/ws/lib/websocket.js:198:10)\n    at TLSSocket.socketOnClose (/home/mynode/git/typescript-node-minimal/node_modules/ws/lib/websocket.js:886:15)\n    at TLSSocket.emit (events.js:203:15)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at _handle.close (net.js:607:12)\n    at TCP.done (_tls_wrap.js:388:7)","type":"Error","msg":"Connection closed"}
{"level":50,"time":1618061277953,"pid":481383,"hostname":"mynode","stack":"Error: introducer.chia.net:8444 did not respond after 20.00 seconds. Bailing.\n    at Timeout.setTimeout (/home/mynode/git/typescript-node-minimal/node_modules/chia-network-scanner/PeerConnection.ts:119:53)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","type":"Error","msg":"introducer.chia.net:8444 did not respond after 20.00 seconds. Bailing."}
fin introducer.chia.net:8444 null
```

**Comment by liuxingbaoyu** [comment]
https://github.com/freddiecoleman/chia-network-scanner/blob/main/encoder.ts#L7-L8
You can replace it with
```js
request_peers: 63,
respond_peers: 64
```
